[package]
name = "tachibana"
version = "0.1.0"
authors = ["Dream Imperium Team <mail@dreamimperium.tk>"]
edition = "2018"

[profile.release]
lto = "thin"

[dependencies]
skulpin-renderer = "0.5"
skulpin-renderer-sdl2 = "0.5"